//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation_SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_CHECK_INS_TODAY
    {
        public int RES_ID { get; set; }
        public byte ROOM_NO { get; set; }
        public byte ADMIN_ID { get; set; }
        public Nullable<byte> CUST_ID { get; set; }
        public System.DateTime DATE_ARRIVE { get; set; }
        public System.DateTime DATE_DEPART { get; set; }
        public decimal TOTAL_COST { get; set; }
        public string CHECK_IN { get; set; }
        public string CHECK_OUT { get; set; }
        public string RES_STATUS { get; set; }
    }
}
