//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation_SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GET_CUST_NAME_FOR_CANCEL
    {
        public int RES_ID { get; set; }
        public string FORENAME { get; set; }
        public string SURNAME { get; set; }
    }
}
