//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation_SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMS_NOT_CURRENTLY_IN_USE
    {
        public byte ROOM_NO { get; set; }
        public string ROOM_TYPE { get; set; }
        public string STATUS { get; set; }
    }
}
